# Generated by Django 5.1.6 on 2025-03-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_name_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
