# Generated by Django 5.1.6 on 2025-03-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_description_alter_products_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
