# Generated by Django 5.1.6 on 2025-03-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Order Creation Date')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('requires_delivery', models.BooleanField(default=False, verbose_name='Requires Delivery')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Delivery Address')),
                ('payment_on_get', models.BooleanField(default=False, verbose_name='Cash on Delivery')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid')),
                ('status', models.CharField(default='Processing', max_length=50, verbose_name='Order Status')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Price')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Sale Date')),
            ],
            options={
                'verbose_name': 'Sold Product',
                'verbose_name_plural': 'Sold Products',
                'db_table': 'order_item',
                'ordering': ('id',),
            },
        ),
    ]
